Repository taozhi8833998/node-sql-parser, pull requests merged in 2024-04, with the labels that each got.

#1849 fix: slow deep nest function sql in all db
  ast/postgresql.ts
  pegjs/athena.pegjs
  pegjs/bigquery.pegjs
  pegjs/db2.pegjs
  pegjs/flinksql.pegjs
  pegjs/hive.pegjs
  pegjs/mariadb.pegjs
  pegjs/mysql.pegjs
  pegjs/noql.pegjs
  pegjs/postgresql.pegjs
  pegjs/redshift.pegjs
  pegjs/snowflake.pegjs
  pegjs/sqlite.pegjs
  pegjs/transactsql.pegjs
  pegjs/trino.pegjs
  test/mysql-mariadb.spec.js
  test/trino.spec.js
Labels: bug, enhancement

#1855 chore: improve create_definitions types
  types.d.ts
Labels: enhancement

#1856 feat: support traversing semi-structured data with colons(:) in snowflake
  pegjs/snowflake.pegjs
  src/column.js
  test/snowflake.spec.js
Labels: enhancement

#1867 fix: count args in mysql
  pegjs/mariadb.pegjs
  pegjs/mysql.pegjs
  src/binary.js
  test/mysql-mariadb.spec.js
Labels: bug

#1869 Fix alter table after mysql
  package-lock.json
  pegjs/mariadb.pegjs
  pegjs/mysql.pegjs
  src/alter.js
  test/mysql-mariadb.spec.js
Labels: bug

#1870 fix: json as table function in pg
  pegjs/postgresql.pegjs
  test/postgres.spec.js
Labels: enhancement

#1871 feat: support temporal table in tsql
  pegjs/transactsql.pegjs
  src/tables.js
  test/transactsql.spec.js
Labels: enhancement

#1873 feat: support declaritive partitions in pg
  pegjs/postgresql.pegjs
  src/create.js
  test/postgres.spec.js
Labels: enhancement

#1868 fix: auto generated types
  ast/postgresql.ts
  pegjs/postgresql.pegjs
Labels: enhancement

#1878 feat: support more set stmt in tsql
  pegjs/transactsql.pegjs
  src/assign.js
  test/transactsql.spec.js
Labels: enhancement

#1880 feat: support map expr in flink
  pegjs/flinksql.pegjs
  src/expr.js
  test/flink.spec.js
Labels: enhancement

#1881 fix: check constraint in mysql
  pegjs/mariadb.pegjs
  pegjs/mysql.pegjs
  test/mysql-mariadb.spec.js
Labels: bug

#1883 fix: broken type generator
  ast/postgresql.ts
  package-lock.json
  package.json
  pegjs/postgresql.pegjs
Labels: enhancement

#1882 feat: support json object in flinksql
  pegjs/flinksql.pegjs
  src/expr.js
  src/func.js
  test/flink.spec.js
Labels: enhancement

#1887 refactor: upgrade version
  package.json
Labels: enhancement

#1888 refactor: update github action to v4
  .github/workflows/npm-publish-github-packages.yml
Labels: enhancement

#1890 refactor: update github action
  .github/workflows/manual.yml
  .github/workflows/npm-publish-github-packages.yml
Labels: enhancement
