Repository taozhi8833998/node-sql-parser, pull requests merged in 2024-11, with the labels that each got.

#2205 feat: support at time zone in pg
  pegjs/postgresql.pegjs
  src/column.js
  src/expr.js
  test/postgres.spec.js
  types.d.ts
Labels: enhancement

#2208 fix: with recursive in pg
  pegjs/athena.pegjs
  pegjs/bigquery.pegjs
  pegjs/db2.pegjs
  pegjs/flinksql.pegjs
  pegjs/hive.pegjs
  pegjs/mariadb.pegjs
  pegjs/mysql.pegjs
  pegjs/noql.pegjs
  pegjs/postgresql.pegjs
  pegjs/redshift.pegjs
  pegjs/snowflake.pegjs
  pegjs/sqlite.pegjs
  pegjs/transactsql.pegjs
  pegjs/trino.pegjs
  test/select.spec.js
Labels: bug

#2209 fix: not null position after generated column in mysql
  src/column.js
  test/create.spec.js
  test/mysql-mariadb.spec.js
Labels: bug

#2210 fix: from clause with multiple parentheses in mysql
  pegjs/mariadb.pegjs
  pegjs/mysql.pegjs
  src/tables.js
  test/mysql-mariadb.spec.js
  types.d.ts
Labels: bug

#2211 feat: support lateral derived tables in mysql
  pegjs/mariadb.pegjs
  pegjs/mysql.pegjs
  test/mysql-mariadb.spec.js
Labels: enhancement

#2213 feat: support set time zone in pg
  pegjs/postgresql.pegjs
  src/assign.js
  test/postgres.spec.js
Labels: enhancement

#2214 refactor: upgrade version
  ast/postgresql.ts
  package.json
Labels: enhancement

#2216 refactor: support if not exists stmt in create index stmt in pg
  pegjs/postgresql.pegjs
  test/postgres.spec.js
Labels: enhancement

#2218 refactor: support listagg function in snowflake
  pegjs/snowflake.pegjs
  test/snowflake.spec.js
Labels: enhancement

#2222 feat: support filter function in athena
  pegjs/athena.pegjs
  test/athena.spec.js
Labels: enhancement

#2228 fix: key as column in athena
  pegjs/athena.pegjs
  test/athena.spec.js
Labels: bug, enhancement

#2229 refactor: as can be ignore when UNNEST in athena
  pegjs/athena.pegjs
  test/athena.spec.js
Labels: enhancement

#2231 feat: support include columns in create index for pg
  pegjs/postgresql.pegjs
  src/create.js
  test/postgres.spec.js
Labels: enhancement

#2233 fix: don't require column expression for alter first
  pegjs/mariadb.pegjs
  src/alter.js
  test/cmd.spec.js
  test/mysql-mariadb.spec.js
Labels: bug

#2234 refactor: alter table first with optional column in mysql
  pegjs/mysql.pegjs
  pegjs/sqlite.pegjs
  src/alter.js
Labels: bug

#2239 Fix vulnerabilities via npm audit fix
  package-lock.json
Labels: security

#2242 feat: support float4 and float8 in snowflake
  pegjs/snowflake.pegjs
  test/snowflake.spec.js
Labels: enhancement

#2243 fix: double quoted table mentions in athena and tsql
  pegjs/athena.pegjs
  pegjs/transactsql.pegjs
  test/athena.spec.js
  test/transactsql.spec.js
Labels: bug

#2244 fix: support real type in athena
  pegjs/athena.pegjs
Labels: bug, enhancement

#2245 feat: support subquery in limit clause
  pegjs/postgresql.pegjs
  test/postgres.spec.js
Labels: enhancement
